apiVersion: v1
kind: Secret
metadata:
  name: user-jhpdp
  namespace: cattle-local-user-passwords
  annotations:
    cattle.io/password-hash: pbkdf2sha3512
type: Opaque
data:
  password: +sMcj9iLBv+jva+VJ/KDXw7ot2psSmPturw+bjhkMyE=
  salt: rd/9o8niZz2DYASW9D+uBce7YHszJYm8w4uFICb6pPs=
