---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: rancher:apps/Deployment:cattle-system/rancher
      deployment.kubernetes.io/revision: '1'
      field.cattle.io/publicEndpoints: '[{"addresses":["10.11.4.11","10.11.4.12","10.11.4.13","10.11.4.14"],"port":80,"protocol":"HTTP","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.dev.net","path":"/","allNodes":false}]'
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"rancher:apps/Deployment:cattle-system/rancher"},"labels":{"app":"rancher","chart":"rancher-2.13.1","heritage":"Helm","release":"rancher"},"name":"rancher","namespace":"cattle-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rancher"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"rancher","release":"rancher"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/os","operator":"NotIn","values":["windows"]}]}]}},"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["rancher"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"containers":[{"args":["--no-cacerts","--http-listen-port=80","--https-listen-port=443","--add-local=true"],"env":[{"name":"CATTLE_NAMESPACE","value":"cattle-system"},{"name":"CATTLE_PEER_SERVICE","value":"rancher"},{"name":"CATTLE_BOOTSTRAP_PASSWORD","valueFrom":{"secretKeyRef":{"key":"bootstrapPassword","name":"bootstrap-secret"}}},{"name":"IMPERATIVE_API_DIRECT","value":"true"},{"name":"IMPERATIVE_API_APP_SELECTOR","value":"rancher"},{"name":"CATTLE_SERVER_URL","value":"https://rancher.dev.net"}],"image":"rancher/rancher:v2.13.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/healthz","port":80},"periodSeconds":30,"timeoutSeconds":5},"name":"rancher","ports":[{"containerPort":80,"protocol":"TCP"},{"containerPort":6666,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":5,"httpGet":{"path":"/healthz","port":80},"periodSeconds":30,"timeoutSeconds":5},"startupProbe":{"failureThreshold":12,"httpGet":{"path":"/healthz","port":80},"periodSeconds":10,"timeoutSeconds":5},"volumeMounts":null}],"priorityClassName":"rancher-critical","serviceAccountName":"rancher","tolerations":[{"effect":"NoSchedule","key":"cattle.io/os","operator":"Equal","value":"linux"}],"volumes":null}}}}

        '
    creationTimestamp: '2026-01-30T21:50:05Z'
    generation: 2
    labels:
      app: rancher
      chart: rancher-2.13.1
      heritage: Helm
      release: rancher
    name: rancher
    namespace: cattle-system
    resourceVersion: '28140'
    uid: 42127142-c28c-4373-a6a4-68c7d2aa38b0
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: rancher
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: rancher
          release: rancher
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: NotIn
                  values:
                  - windows
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rancher
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - args:
          - --no-cacerts
          - --http-listen-port=80
          - --https-listen-port=443
          - --add-local=true
          env:
          - name: CATTLE_NAMESPACE
            value: cattle-system
          - name: CATTLE_PEER_SERVICE
            value: rancher
          - name: CATTLE_BOOTSTRAP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: bootstrapPassword
                name: bootstrap-secret
          - name: IMPERATIVE_API_DIRECT
            value: 'true'
          - name: IMPERATIVE_API_APP_SELECTOR
            value: rancher
          - name: CATTLE_SERVER_URL
            value: https://rancher.dev.net
          image: rancher/rancher:v2.13.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: rancher
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 6666
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        priorityClassName: rancher-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: rancher
        serviceAccountName: rancher
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: '2026-01-30T21:50:05Z'
      lastUpdateTime: '2026-01-30T21:51:26Z'
      message: ReplicaSet "rancher-58cf7b89d9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2026-01-30T23:28:16Z'
      lastUpdateTime: '2026-01-30T23:28:16Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: rancher:/Service:cattle-system/rancher
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"rancher:/Service:cattle-system/rancher"},"labels":{"app":"rancher","chart":"rancher-2.13.1","heritage":"Helm","release":"rancher"},"name":"rancher","namespace":"cattle-system"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80},{"name":"https-internal","port":443,"protocol":"TCP","targetPort":444}],"selector":{"app":"rancher"}}}

        '
    creationTimestamp: '2026-01-30T21:50:05Z'
    labels:
      app: rancher
      chart: rancher-2.13.1
      heritage: Helm
      release: rancher
    name: rancher
    namespace: cattle-system
    resourceVersion: '2351'
    uid: ac92473f-c060-4b10-95ad-96986838dea6
  spec:
    clusterIP: 10.43.67.191
    clusterIPs:
    - 10.43.67.191
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https-internal
      port: 443
      protocol: TCP
      targetPort: 444
    selector:
      app: rancher
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: rancher:networking.k8s.io/Ingress:cattle-system/rancher
      field.cattle.io/publicEndpoints: '[{"addresses":["10.11.4.11","10.11.4.12","10.11.4.13","10.11.4.14"],"port":80,"protocol":"HTTP","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.dev.net","path":"/","allNodes":false}]'
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"rancher:networking.k8s.io/Ingress:cattle-system/rancher","nginx.ingress.kubernetes.io/proxy-connect-timeout":"30","nginx.ingress.kubernetes.io/proxy-read-timeout":"1800","nginx.ingress.kubernetes.io/proxy-send-timeout":"1800","nginx.ingress.kubernetes.io/ssl-redirect":"false"},"labels":{"app":"rancher","chart":"rancher-2.13.1","heritage":"Helm","release":"rancher"},"name":"rancher","namespace":"cattle-system"},"spec":{"ingressClassName":"traefik","rules":[{"host":"rancher.dev.net","http":{"paths":[{"backend":{"service":{"name":"rancher","port":{"number":80}}},"path":"/","pathType":"ImplementationSpecific"}]}}]}}

        '
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    creationTimestamp: '2026-01-30T21:50:05Z'
    generation: 1
    labels:
      app: rancher
      chart: rancher-2.13.1
      heritage: Helm
      release: rancher
    name: rancher
    namespace: cattle-system
    resourceVersion: '2966'
    uid: 13ec9af3-c8f9-4ac8-830f-e30f4a48fcbe
  spec:
    ingressClassName: traefik
    rules:
    - host: rancher.dev.net
      http:
        paths:
        - backend:
            service:
              name: rancher
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
  status:
    loadBalancer:
      ingress:
      - ip: 10.11.4.11
      - ip: 10.11.4.12
      - ip: 10.11.4.13
      - ip: 10.11.4.14
- apiVersion: v1
  data:
    priorityClassName: rancher-critical
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: rancher:/ConfigMap:cattle-system/rancher-config
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"priorityClassName":"rancher-critical"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"rancher:/ConfigMap:cattle-system/rancher-config"},"labels":{"app":"rancher","app.kubernetes.io/part-of":"rancher","chart":"rancher-2.13.1","heritage":"Helm","release":"rancher"},"name":"rancher-config","namespace":"cattle-system"}}

        '
    creationTimestamp: '2026-01-30T21:50:05Z'
    labels:
      app: rancher
      app.kubernetes.io/part-of: rancher
      chart: rancher-2.13.1
      heritage: Helm
      release: rancher
    name: rancher-config
    namespace: cattle-system
    resourceVersion: '2346'
    uid: 67b1b66c-f1c0-4588-ba63-c50185d43d9a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: rancher:/ServiceAccount:cattle-system/rancher
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"rancher:/ServiceAccount:cattle-system/rancher"},"labels":{"app":"rancher","chart":"rancher-2.13.1","heritage":"Helm","release":"rancher"},"name":"rancher","namespace":"cattle-system"}}

        '
      rancher.io/service-account.secret-ref: cattle-system/rancher-token-kxx89
    creationTimestamp: '2026-01-30T21:50:05Z'
    labels:
      app: rancher
      chart: rancher-2.13.1
      heritage: Helm
      release: rancher
    name: rancher
    namespace: cattle-system
    resourceVersion: '2450'
    uid: c14f2c71-05b1-4a41-9a08-e6f7c0387cb1
kind: List
metadata: {}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: rancher
    chart: rancher-2.13.1
    heritage: Helm
    release: rancher
  name: rancher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rancher
  namespace: cattle-system

