# Source: actions-runner-controller/templates/manager_role_binding_secrets.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: actions-runner-controller-manager-secrets
  namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actions-runner-controller-manager-secrets
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: actions-runner-system
