# Source: actions-runner-controller/templates/leader_election_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: actions-runner-controller-leader-election
  namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: actions-runner-controller-leader-election
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: actions-runner-system
