# Source: actions-runner-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: actions-runner-controller
  namespace: actions-runner-system
  labels:
    helm.sh/chart: actions-runner-controller-0.23.7
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: actions-runner-controller
    app.kubernetes.io/version: "0.27.6"
    app.kubernetes.io/managed-by: Helm
