apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yugabytedb-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/swipentap/prod.git
    targetRevision: main
    path: manifests
    directory:
      recurse: false
      include: yugabytedb-ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yugabytedb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
