apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
  namespace: cockroachdb
spec:
  image:
    name: cockroachdb/cockroach:v25.2.4
    pullPolicy: IfNotPresent
  dataStore:
    pvc:
      source:
        claimName: ""
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: "local-path"
        volumeMode: Filesystem
    supportsAutoResize: false
  nodes: 3
  tlsEnabled: true
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  maxUnavailable: 1
  grpcPort: 26258
  httpPort: 8080
  sqlPort: 26257
