apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yugabytedb-master-ui
  namespace: yugabytedb
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: db.dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yb-master-ui
                port:
                  number: 7000
  tls: []
