# Source: actions-runner-controller/templates/webhook_service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: actions-runner-controller-webhook
  namespace: actions-runner-system
  labels:
    helm.sh/chart: actions-runner-controller-0.23.7
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: actions-runner-controller
    app.kubernetes.io/version: "0.27.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: actions-runner-controller
