apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgresql-ingress
  namespace: postgresql
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
  - host: pgsql.prod.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postgresql-rw
            port:
              number: 5432
  tls:
  - hosts:
    - pgsql.prod.net
    secretName: tls-prod-net-wildcard
