apiVersion: v1
kind: Service
metadata:
  name: postgresql-rw-nodeport
  namespace: postgresql
spec:
  type: NodePort
  selector:
    postgresql.cnpg.io/cluster: postgresql
    postgresql.cnpg.io/instanceRole: primary
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
    nodePort: 30432