apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonar
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: postgresql
  owner: postgres
  database: sonar
